name: Update README on Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}